### ISSUE TITLE
Target names not shown in command palette

### ISSUE THREAD

**Issue by simonvanderveldt** [mdeboer/build-platformio#4]
Thanks for making this integration with atom-build!

Quick question/issue:
The build targets are all listed with the same description "Platformio Ide: Target" in the command palette
![image](https://user-images.githubusercontent.com/204286/77679394-c63cc080-6f92-11ea-9229-4a75673adc92.png)
Seems like something is going wrong somewhere?

And maybe it would be better to drop the "Ide" part of those names as well, it got me confused for a second thinking I accidentally installed (parts of) the platformio-ide packages.

I'm using atom 1.44, atom-build 0.70.0 and build-platformio 1.2.4

**Comment by mdeboer** [comment]
I suppose the API has changed, I'll update asap!

**Comment by mdeboer** [comment]
Hey @simonvanderveldt 

It's been a long time since I last used this package (I don't use Atom any more unfortunately) but I think I managed to updated the package for you. I got the newest build provider from their [platformio-atom-ide](https://github.com/platformio/platformio-atom-ide/tree/v2.6.0) package (v2.6.0).

Unfortunately I wasn't able to test it right now and I'm hoping you can give it a spin. Go to my [development](https://github.com/Cloudstek/build-platformio/tree/develop) branch and clone or download it as zip. Extract it to your Atom packages directory and make sure to name the directory `build-platformio`.

I hope everything works for you!

As for the name change in the commands, I can't really help you there as it's really the build provider written by them. So in fact it is a small part of the `platformio-ide` package but not officially.

Please let me know how it went!
